version: "2"
services: 
  sut:
    build:
      context: .
      dockerfile: dockerfile.test 
    environment: 
      - NODE_ENV=test
    links:
      - api
  mongodb:
    image: mongo
    container_name: db
  mongo-data:
    build:
      context: ./mongo-data
    container_name: mongo.data
    links:
      - mongodb
  api:
    build: .
    command: "npm start"
    container_name: api.movie
    environment: 
      - PORT=1453
      - NODE_ENV=development
      - DB_URL=mongodb://db:27017/moviedb
    links:
      - mongodb
      - mongo-data
    volumes:
      - ./test:/sutbox/test
