version: "2"
services: 
  mongodb:
    image: mongo
    container_name: db
    ports: 
      - "27017:27017"
  mongo-sidercar:
    build: ./mongo-sidecar
    links:
      - mongodb
  api:
    build: .
    command: npm start
    ports: 
      - "1453:1453"
      - "5858:5858"
    environment: 
      - NODE_ENV=development
      - PORT=1453
      - DB_HOST=db
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_NAME=moviedb
    links:
      - mongodb
      - mongo-sidercar
    volumes: 
      - .:/app