version: "2"
services: 
  mongodb:
    image: mongo
    container_name: db
  mongo-data:
    build: ./mongo-data
    links:
      - mongodb
  api:
    build: .
    command: npm start
    environment: 
      - PORT=1453
      - NODE_ENV=development
      - DB_URL=mongodb://db:27017/moviedb
    ports: 
      - "1453:1453"
      - "5858:5858"
    links:
      - mongodb
      - mongo-data
    volumes: 
      # Docker for Windows
      # .:/app
      # Docker Machine
      - /usr/app:/app/