FROM node
MAINTAINER "Ahmet Atar <ahhmetatar@gmail.com>"

COPY package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /sutbox && cp -a /tmp/node_modules /sutbox/ && cp -a /tmp/package.json /sutbox/package.json && mkdir -p /sutbox/test

COPY test/movies.spec.js /sutbox/test/movies.spec.js
WORKDIR /sutbox

CMD ["node_modules/mocha/bin/mocha"]