version: "2"
services: 
  mongodb:
    image: mongo
    container_name: db
  mongo-data:
    build: ./mongo-data
    links:
      - mongodb
  api:
    build: .
    environment: 
      - PORT=1453
      - NODE_ENV=test
      - DB_URL=mongodb://db:27017/moviedb
    links:
      - mongodb
      - mongo-data
    volumes: 
      # Docker for Windows
      - .:/app
      # Docker Machine
      #- /usr/app:/app/