version: "2"
services: 
  mongodb:
    image: mongo
    container_name: db
    ports: 
      - "27017:27017"
  mongo-data:
    build: ./mongo-data
    links:
      - mongodb
  api:
    build: .
    command: npm start
    ports: 
      - "1453:1453"
      - "5858:5858"
    environment: 
      - NODE_ENV=development
      - PORT=1453
      - DB_URL=mongodb://db:27017/moviedb
    links:
      - mongodb
      - mongo-data
    volumes: 
      - .:/app