apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: movierecapi-deployment
  labels:
    app: movie-rec-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-rec-api
  template:
    metadata:
      labels:
        app: movie-rec-api
    spec:
      containers:
        - name: movie-rec-api
          image: asia.gcr.io/movierecapi/apimg
          ports:
            - containerPort: 1453
          env:
            - name: DB_AUTH
              value: "true"
            - name: NODE_ENV
              value: production
            - name: APP_VERSION
              value: "1.0.109"
            - name: DEBUG
              value: "app*"
            - name: PORT
              value: "1453"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apisecrets
                  key: dbusername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apisecrets
                  key: dbpassword
            - name: DB_HOST
              value: "10.140.0.5"                           
            - name: DB_NAME
              value: moviedb
            - name: DB_PORT
              value: "27017"                            
          livenessProbe:
            httpGet:
              path: /health
              port: 1453
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 1453
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 1
