apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: movierecapi-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: movie-rec-api
    spec:
      containers:
        - name: movie-rec-api
          image: asia.gcr.io/movie-rec-api/api
          imagePullPolicy: Always
          ports:
            - containerPort: 1453
          env:
            - name: PORT
              value: "1453"
            - name: DB_URL
              value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/moviedb?replicaSet=rs0
          livenessProb:
            httpGet:
              path: /health
              port: 1453
              initialDelaySeconds: 10
              periodSeconds: 15
              failureThreshold: 2
              timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 1453
              initialDelaySeconds: 5
              periodSeconds: 2
              failureThreshold: 1
              timeoutSeconds: 1
