apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: movierecapi-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: movie-rec-api
    spec:
      containers:
        - name: movie-rec-api
          image: asia.gcr.io/movie-rec-api/api
          imagePullPolicy: Always
          ports:
            - containerPort: 1453
          env:
            - name: PORT
              value: "1453"
            - name: DB_URL
              value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/moviedb?replicaSet=rs0
              #valueFrom: 
              #  secretKeyRef:
              #    name: appsecrets
              #    key: dburl